name: Example Validation Workflow
on:
  push:
    branches:
      - master
    paths:
      - 'examples/2_0-Metabolomics_Release/**'
  pull_request:
    branches:
      - master
    paths:
      - 'examples/2_0-Metabolomics_Release/**'
jobs:
  validate-examples:
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os:
          - ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Validate Examples
        run: ./validate.sh
        shell: bash
